-- Reverts 20261008185149_init. Prisma has no native down migrations; apply with:
--   prisma db execute --file prisma/migrations/20261008185149_init/down.sql
-- The last statement removes the migration record, so `prisma migrate deploy`
-- re-applies it afterwards (`migrate resolve --rolled-back` only accepts failed migrations).
-- Destroys ALL application data. Never run against production without a backup.

-- Hand-written section (CASCADE also drops the triggers that use these functions).
DROP FUNCTION IF EXISTS "app_check_transaction_owner"() CASCADE;
DROP FUNCTION IF EXISTS "app_check_planning_owner"() CASCADE;
DROP FUNCTION IF EXISTS "app_check_investment_owner"() CASCADE;
DROP FUNCTION IF EXISTS "app_check_category_owner"() CASCADE;
DROP FUNCTION IF EXISTS "app_check_spreadsheet_ref_owner"() CASCADE;
DROP FUNCTION IF EXISTS "app_check_action_history_owner"() CASCADE;
DROP FUNCTION IF EXISTS "app_prevent_owner_change"() CASCADE;
DROP FUNCTION IF EXISTS "app_assert_same_owner"(regclass, uuid, uuid);
DROP INDEX IF EXISTS "spreadsheets_one_active_per_owner_key";

-- Generated by: prisma migrate diff --from-schema prisma/schema.prisma --to-empty --script
-- DropForeignKey
ALTER TABLE "public"."user_roles" DROP CONSTRAINT "user_roles_user_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."user_roles" DROP CONSTRAINT "user_roles_role_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."user_profiles" DROP CONSTRAINT "user_profiles_user_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."voice_preferences" DROP CONSTRAINT "voice_preferences_user_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."google_connections" DROP CONSTRAINT "google_connections_user_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."system_settings" DROP CONSTRAINT "system_settings_updated_by_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."spreadsheets" DROP CONSTRAINT "spreadsheets_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."financial_accounts" DROP CONSTRAINT "financial_accounts_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."categories" DROP CONSTRAINT "categories_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."categories" DROP CONSTRAINT "categories_parent_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."transactions" DROP CONSTRAINT "transactions_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."transactions" DROP CONSTRAINT "transactions_spreadsheet_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."transactions" DROP CONSTRAINT "transactions_account_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."transactions" DROP CONSTRAINT "transactions_transfer_account_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."transactions" DROP CONSTRAINT "transactions_category_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."transactions" DROP CONSTRAINT "transactions_investment_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."transactions" DROP CONSTRAINT "transactions_installment_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."transactions" DROP CONSTRAINT "transactions_recurring_transaction_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."investments" DROP CONSTRAINT "investments_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."investments" DROP CONSTRAINT "investments_account_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."recurring_transactions" DROP CONSTRAINT "recurring_transactions_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."recurring_transactions" DROP CONSTRAINT "recurring_transactions_spreadsheet_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."recurring_transactions" DROP CONSTRAINT "recurring_transactions_account_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."recurring_transactions" DROP CONSTRAINT "recurring_transactions_category_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."installments" DROP CONSTRAINT "installments_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."installments" DROP CONSTRAINT "installments_spreadsheet_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."installments" DROP CONSTRAINT "installments_account_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."installments" DROP CONSTRAINT "installments_category_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."conversations" DROP CONSTRAINT "conversations_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."conversations" DROP CONSTRAINT "conversations_spreadsheet_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."conversation_messages" DROP CONSTRAINT "conversation_messages_conversation_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."conversation_messages" DROP CONSTRAINT "conversation_messages_action_history_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."ai_configurations" DROP CONSTRAINT "ai_configurations_provider_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."reports" DROP CONSTRAINT "reports_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."reports" DROP CONSTRAINT "reports_spreadsheet_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."action_history" DROP CONSTRAINT "action_history_owner_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."action_history" DROP CONSTRAINT "action_history_conversation_id_fkey";

-- DropTable
DROP TABLE "public"."users";

-- DropTable
DROP TABLE "public"."roles";

-- DropTable
DROP TABLE "public"."user_roles";

-- DropTable
DROP TABLE "public"."user_profiles";

-- DropTable
DROP TABLE "public"."voice_preferences";

-- DropTable
DROP TABLE "public"."google_connections";

-- DropTable
DROP TABLE "public"."system_settings";

-- DropTable
DROP TABLE "public"."spreadsheets";

-- DropTable
DROP TABLE "public"."financial_accounts";

-- DropTable
DROP TABLE "public"."categories";

-- DropTable
DROP TABLE "public"."transactions";

-- DropTable
DROP TABLE "public"."investments";

-- DropTable
DROP TABLE "public"."recurring_transactions";

-- DropTable
DROP TABLE "public"."installments";

-- DropTable
DROP TABLE "public"."conversations";

-- DropTable
DROP TABLE "public"."conversation_messages";

-- DropTable
DROP TABLE "public"."ai_providers";

-- DropTable
DROP TABLE "public"."ai_configurations";

-- DropTable
DROP TABLE "public"."reports";

-- DropTable
DROP TABLE "public"."action_history";

-- DropEnum
DROP TYPE "public"."UserStatus";

-- DropEnum
DROP TYPE "public"."RoleName";

-- DropEnum
DROP TYPE "public"."AppLocale";

-- DropEnum
DROP TYPE "public"."VoiceGender";

-- DropEnum
DROP TYPE "public"."GoogleConnectionStatus";

-- DropEnum
DROP TYPE "public"."SpreadsheetStatus";

-- DropEnum
DROP TYPE "public"."SyncStatus";

-- DropEnum
DROP TYPE "public"."FinancialAccountType";

-- DropEnum
DROP TYPE "public"."CategoryKind";

-- DropEnum
DROP TYPE "public"."TransactionType";

-- DropEnum
DROP TYPE "public"."TransactionStatus";

-- DropEnum
DROP TYPE "public"."PaymentMethod";

-- DropEnum
DROP TYPE "public"."RecurrenceFrequency";

-- DropEnum
DROP TYPE "public"."RecurrenceIntervalUnit";

-- DropEnum
DROP TYPE "public"."InvestmentClass";

-- DropEnum
DROP TYPE "public"."ConversationMessageRole";

-- DropEnum
DROP TYPE "public"."AIProviderType";

-- DropEnum
DROP TYPE "public"."AIPurpose";

-- DropEnum
DROP TYPE "public"."ReportType";

-- DropEnum
DROP TYPE "public"."ReportFormat";

-- DropEnum
DROP TYPE "public"."ReportStatus";

-- DropEnum
DROP TYPE "public"."ActionEntityType";

-- DropEnum
DROP TYPE "public"."ActionKind";


-- Forget the migration so it can be re-applied.
DELETE FROM "_prisma_migrations" WHERE "migration_name" = '20261008185149_init';
